### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


In [2]:
import numpy as np

###### 1. Write a NumPy program to find the missing data in a given array.

In [40]:
### code here
K = np.array([[3,2,np.nan,1],[10,12,10,9],[5,np.nan,1,np.nan]])
print(K)
print("\nFind the missing data of the said array:")
print(np.isnan(K))

[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [11]:
### code here 
s = [1,2,3]
A = np.array(s)
print(A)
s1 = [1,2,6]
B = np.array(s1)
print(B)
print(A == B)

[1 2 3]
[1 2 6]
[ True  True False]


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [29]:
## code here
print("Original array:")
S = np.arange(0,16).reshape(4,4)
print(S)
print(" ")
print("New array after swapping first and last rows of the said array:")
S[[0,3],:] = S[[3,0],:]
print(S)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
 
New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [63]:
#### code here
list = [1,2,3,4]
A = np.array(list)
print(list)
print(A)

[1, 2, 3, 4]
[1 2 3 4]


In [60]:
tuple = (1,2,3,4)
A = np.array(tuple)
print(tuple)
print(A)

(1, 2, 3, 4)
[1 2 3 4]


###### 5. Write a NumPy program to find common values between two arrays.

In [76]:
### code here
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = np.array([10, 30, 40])
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10 30 40]
Common values between two arrays:
[10 40]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [44]:
### code here
s = np.array([[1,2],[3,4],[5,6]])
print("Reshape 3x2:")
print(s)
print("Reshape 2x3:")
print(s.reshape(2,3))

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [74]:
### code here
r = np.array([10 ,10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])
print("Original array:")
print(r)
a,b = np.unique(r,return_counts=True) 
print("Frequency of unique values of the said array:")
print(np.asarray((a,b)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [57]:
### code here
print("Original arrays:\nArray-1")
x = np.array([[0,0,0],[1,2,3],[4,5,6]])
print(x)
print("Array-2")
s = np.array([10,11,12])
print(s)
print("\nNew Array:")
print(x + s)

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [51]:
### code here
d = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(d)
print("\nExtracted data: Second row")
print(d[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [48]:
## code here
l = np.arange(0,16).reshape(4,4)
print("Original array:")
print(l)
print("\nExtracted data: Third and fourth elements of the first and second rows ")
print(l[0:2,2:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [77]:
### code here
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2022-10-27
Today:  2022-10-28
Tomorrow:  2022-10-29


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [96]:
## code here
import numpy as np
print("First Monday in May 2017:")
print(np.busday_offset('2022-05', 0, roll='forward', weekmask='Sat'))

First Monday in May 2017:
2022-05-07
