### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [4]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [15]:
print("An array of 10 zeros:")
print(np.zeros((10)))
print("An array of 10 ones:")
print(np.ones((10)))
print("An array of 10 fives:")
print(np.array([5,5,5,5,5,5,5,5,5,5],dtype = float))

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [16]:
print("An array of 10 zeros:")
print(np.zeros((10)))
print("An array of 10 ones:")
print(np.ones((10)))
print("An array of 10 fives:")
print(np.ones(10)*5)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [18]:
### code here
print("Array of the integers from 30 to 70")
print(np.arange(30,71))

Array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [19]:
### code here
print("Array of all the even integers from 10 to 50")
print(np.arange(10,50,2))

Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [27]:
### code here
print("3x3 matrix:")
print(np.eye(3))

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [8]:
### code here
print("Random number between 0 and 1:")
A = np.random.rand(1)
print(A)

Random number between 0 and 1:
[0.7013174]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [95]:
## code here
print("15 random numbers from a standard normal distribution:")
print(np.random.randn(15))

15 random numbers from a standard normal distribution:
[-0.10028612  2.1018053   1.08197826  0.8619869  -1.62072954  0.57078937
 -0.45740124  1.99345181  1.93090497 -1.03447437  0.88762364 -0.43876782
  1.37282647 -0.9613749   0.4542879 ]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [112]:
print("Original array:")
A = [[10,11,12,13],[14,15,16,17],[18,19,20,21]]
print(np.array(A))
B = np.array(A)
print("Each element of the array is:")
for i in B.flatten():
    print(i,end = " ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [122]:
print("Original array:")
A = np.arange(10,22).reshape(3,4)
print(A)
print("Each element of the array is:")
for i in A.flatten():
    print(i,end = " ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [118]:
## code here
s = [1,8,3,5]
K = [10,1,4,10]
S1 = np.array(s)
K1 = np.array(K)
print("Vector-1")
print(S1)
print("Vector-2")
print(K1)
print("Multiply the values of two said vectors:")
print(S1 * K1)

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [7]:
### code here
print("Original array:")
print(np.arange(12,38))
print("Reverse array:")
print(np.arange(37,11,-1))

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [28]:
print("Original array:")
S = np.arange(12,38)
print(S)
print("Reverse array:")
print(np.flip(S))

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [44]:
## code here
a = np.zeros((5,5),dtype=int)
np.fill_diagonal(a,[1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [24]:
## code here
print("Original array:")
A = [[0,1],[2,3]]
B = np.array(A)
print(B)
print("Sum of all elements:")
print(np.sum(A))
print("Sum of each column:")
print(np.sum(A,axis = 0))
print("Sum of each row:")
print(np.sum(A,axis = 1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [52]:
## code here 
print("Original vectors:")
s = [4,5]
s1 = np.array(s)
print(s1)
k = [7,10]
k1 = np.array(k)
print(k1)
A = s1 * k1
print("Inner product of said vectors:")
print(np.sum(A))

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
